In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("Autism-Adult-Data.csv")
df.head()

A1_Score  A2_Score  A3_Score  A4_Score  A5_Score  A6_Score  A7_Score  \
0         1         1         1         1         0         0         1   
1         1         1         0         1         0         0         0   
2         1         1         0         1         1         0         1   
3         1         1         0         1         0         0         1   
4         1         0         0         0         0         0         0   

   A8_Score  A9_Score  A10_Score  age  gender  jundice  austi0  \
0         1         0          0   26       1        0       0   
1         1         0          1   24       0        0       1   
2         1         1          1   27       0        1       1   
3         1         0          1   35       1        0       1   
4         1         0          0   40       1        0       0   

   used_app_be1ore  result  Class/ASD  
0                0       6          0  
1                0       5          0  
2                0       8          1  
3                0       6          0  
4                0       2          0

In [4]:
X = df.iloc[:,0:16]
Y = df.iloc[:,16]

In [5]:
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

In [6]:
test = SelectKBest(score_func=f_classif, k=10)
fit = test.fit(X, Y)
# summarize scores
set_printoptions(precision=3)
print(fit.scores_)
features = fit.transform(X)
# summarize selected features
print(features[0:5,:])

[6.752e+01 7.519e+01 1.677e+02 1.987e+02 2.869e+02 3.760e+02 9.884e+01
 4.136e+01 4.786e+02 1.223e+02 2.415e+00 4.486e+00 7.262e+00 2.250e+01
 1.339e+00 1.461e+03]
[[1 1 1 1 0 0 1 0 0 6]
 [1 1 0 1 0 0 0 0 1 5]
 [1 1 0 1 1 0 1 1 1 8]
 [1 1 0 1 0 0 1 0 1 6]
 [1 0 0 0 0 0 0 0 0 2]]


In [25]:
#A1-A10,result

In [7]:
from sklearn.feature_selection import chi2 

In [8]:
chi2_features = SelectKBest(chi2, k = 10) 
X_kbest_features = chi2_features.fit_transform(X, Y)

In [11]:
X_kbest_features[0]

array([ 1,  1,  1,  0,  0,  1,  0,  0, 26,  6], dtype=int64)

In [ ]:
# A234567910,age,result

In [26]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [27]:
model = LogisticRegression(solver='lbfgs')
rfe = RFE(model, 3)
fit = rfe.fit(X, Y)
print("Num Features: %d" % fit.n_features_)
print("Selected Features: %s" % fit.support_)
print("Feature Ranking: %s" % fit.ranking_)

C:\Users\ASUS\AppData\Roaming\Python\Python37\site-packages\sklearn\utils\validation.py:71: FutureWarning: Pass n_features_to_select=3 as keyword args. From version 0.25 passing these as positional arguments will result in an error
  FutureWarning)
C:\Users\ASUS\AppData\Roaming\Python\Python37\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


Num Features: 3
Selected Features: [False  True False False False  True False False False False False False
 False False False False  True]
Feature Ranking: [15  1  7  9  3  1  4  6  5  2  8 13 11 14 12 10  1]


In [30]:
#A179346528 14 15 11

In [31]:
from sklearn.ensemble import ExtraTreesClassifier

In [32]:
model = ExtraTreesClassifier(n_estimators=10)
model.fit(X, Y)
print(model.feature_importances_)

[0.023 0.04  0.033 0.049 0.067 0.2   0.063 0.036 0.027 0.08  0.024 0.014
 0.007 0.005 0.01  0.003 0.318]


In [ ]:
# 0.08,0.067,0.063,0.049,0.04, 0.036,0.033, 0.027, 0.024, 0.2
# A1-10